### PR TITLE
Support downloading and using older versions of sm-agent

### PR DESCRIPTION
**Pull request by rolandtritsch**
This implements #4.

Note: Even after downloading and using sm-agent version 15 I am still experiencing problems to get the completion to work.

### CODE REVIEW

**Review by crazywolf132 — APPROVED** [review]
LGTM

**Comment by rolandtritsch** [comment]
Hi @crazywolf132. Can you make me a contributor. So that I can merge this.

**Comment by crazywolf132** [comment]
I think, we should look at #8 instead currently @rolandtritsch

**Comment by rolandtritsch** [comment]
Closing this one because it is superseeded by #8.

**Pull request closed without merging**
